apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: argocd
spec:
  syncPolicy:
    automated: 
      prune: false
      selfHeal: true
  project: default
  source:
    chart: postgresql
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 12.2.2
    helm:
      values: |
        global:
          postgresql:
            auth:
              username: postgres
              database: postgres
        primary:
          persistence:
            enabled: false
        metrics:
         enabled: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
# values location https://github.com/bitnami/charts/blob/main/bitnami/postgresql/values.yaml