apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: range-query-example
spec:
  args:
  - name: service-name
  - name: lookback-duration
    value: 5m
  metrics:
  - name: success-rate
    # checks that all returned values are under 1000ms
    successCondition: "all(result, # < 1000)"
    failureLimit: 3
    provider:
      prometheus:
        rangeQuery:
          # See https://expr-lang.org/docs/language-definition#date-functions
          # for value date functions
          # The start point to query from
          start: 'now() - duration("{{args.lookback-duration}}")'
          # The end point to query to
          end: 'now()'
          # Query resolution width 
          step: 1m
        address: http://prometheus.default.cluster.svc.local
        insecure: true
        query: http_latency_ms{service="{{args.service-name}}"}